name: ci

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: setup go
        uses: actions/setup-go@v6
        with:
          go-version: "1.22"
          cache: false

      - name: test with coverage
        run: go test -coverprofile=coverage.out ./...

      - name: upload coverage to codecov
        uses: codecov/codecov-action@v5.4.2
        with:
          files: ./coverage.out
          use_oidc: true
          fail_ci_if_error: false
          plugins: noop
          verbose: true

      - name: build local binary
        run: go build ./cmd/tg-ws-proxy

      - name: build openwrt binary
        run: |
          mkdir -p build
          GOOS=linux GOARCH=mipsle GOMIPS=softfloat go build -trimpath -ldflags="-s -w" -o build/tg-ws-proxy-openwrt ./cmd/tg-ws-proxy
